language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean source:jar deploy --settings travis_settings.xml

# travis encrypt -r bootique/bootique-bom "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique-bom "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "uitlkW4gz+jT0Y7Fl2hquGh+QwKj1ld1EBhsb9FABeKS064WaLpfrztQQXf+eQc1BaRGFGAqowLJUBOxPCY+oIr3ksupxFekbvVP9e3qLnHtRAVQmRBRvZvx6RNnO6/QEWGGtM8Pseln9Y2lfYRBTSOddggLR2FIN7K3cikCLr8RJ8nwJO2ewhD+baJlnlYK+F10TU+us4s3RIYE2F9fbNCFmFZoOgHbDxdL0hZQgXESv/gWgJ1/NaU7hA57LoZ1B4pCOgPJP9mA9154ImdPAiNpBFF7odEjsB7aR52LLUBWb8ou7LLVFZn507YEJhOF2R1YzbWUTK8dbOeJDN5Mi1hV1EQSXxMvZTE4LtpoSA9vkdwslkDui3WQJ3IBWH5HFMNixhjQgjJuEL2iUGcXV6QifVyNRKebB1DcFC4aCUpFRfGDon14Ys1k03k1pSZjum/0RTuBWanbAW9iHUsu6zysDlztq4dan6CQ3twJ5oL05hBECiOmrchdbTLfbWOYGdfzvg/BIND8W9wWnHofw0kkn03Az8O9UTRPoVw77VJOpwWGNqM3ZeKAD9QDb/MVwlzs3fx8+ZLhfznMpDZgb6Wur0XqKwCakYcJg96+Hw2qsx3SpO2KE5QXC6zGcQZpW0yMMZKNXFVM8i5BMmlqRnOwbYEZLOvIe+Vltzh31Ck="
    - secure: "SPiyoNT2lK837dQWx+qLTLOFYkPfjZObOpMsh0hNjPZKAVWt7GD84zqCFT/VIkKapVmVqHI5QH8gQVh8e+4IIDYdBisq13edOE7TJ7rUamNI3VAYTaHHQl0/dJcY1rB2OnNPvL2QBgP51F8mSkzQ/MqY0TzRnBXuRdCinxqpy7cBXSvB4rPGoJWvhi+HWH98VV33hzFDJ93+OyI0IaPpKUpAyKUvyRG0GFTVndWyak0Z8KYHaGY8e5PCbehWg85DhEaHwGM18sOIXXk2RKg0QA4XsgDDoXvN4Rch6Yxp6P9bIPQmzZ9wQu+e4jjvvqhAXwM2foY+jW/xJ92riJUfdDu5ivCVj6C+EVX0BLHaC1HW5BDFu8ShIG80JdrktAAhVDSAVSruRehPbHD3Zk3m9bOf9YX1HlDMuGanfjD+HRt+U+6xTes7MDdN4P98FYcEYerK8zqxg6zRrKJ9x1vQGLK3i7D4MwMWC0teCoi86jmRVcUCnv6f2+jHfal8Nt1a3ropESthBTWwVx7rCIhfUK277d8NTW9/Il7ohgZ9qj7ekl4UC/jF5vL1cWrbl8n8xpQq0dRJUXaCFNVieuRRFM/ig/b3OqbePc7yQAU4hZpnxBYaYR/J2bhDGEVJs2FuKI+mbqua4m6XyMnI1TMvkRXkXwYTR5qNRVw0eg3fhiU="

